config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :list_items
  get 'home/about'
  root 'home#index'
end

app/models/list_item.rb
class ListItem < ApplicationRecord
end

app/controllers/list_items_controller.rb
class ListItemsController < ApplicationController
  before_action :set_list_item, only: %i[ show edit update destroy ]
  helper_method :sort_column, :sort_direction

  ITEM_PER_PAGE = 3

  # GET /items or /items.json
  def index
    @list_items = ListItem.all
    if params[:query]
      @query = params[:query]
      @list_items = @list_items.where('last_name LIKE ?', "%#{@query}%")
    end
    @page = params.fetch(:page, 0).to_i
    @total_pages = (@list_items.length * 1.0 / ITEM_PER_PAGE).ceil
    @list_items = @list_items.offset(@page * ITEM_PER_PAGE).limit(ITEM_PER_PAGE)
    respond_to do |format|
      format.html
      format.json { render json: @list_items }
    end
  end
  # GET /list_items or /list_items.json
  def index
    @list_items = ListItem.order(sort_column + " " + sort_direction)
  end

  # GET /list_items/1 or /list_items/1.json
  def show
  end

  # GET /list_items/new
  def new
    @list_item = ListItem.new
  end

  # GET /list_items/1/edit
  def edit
  end

  # POST /list_items or /list_items.json
  def create
    @list_item = ListItem.new(list_item_params)
    respond_to do |format|
      if @list_item.save
        format.html { redirect_to list_item_url(@list_item), notice: "List item was successfully created." }
        format.json { render :show, status: :created, location: @list_item }
      else
        format.html { render :new, status: :unprocessable_entity }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /list_items/1 or /list_items/1.json
  def update
    respond_to do |format|
      if @list_item.update(list_item_params)
        format.html { redirect_to list_item_url(@list_item), notice: "List item was successfully updated." }
        format.json { render :show, status: :ok, location: @list_item }
      else
        format.html { render :edit, status: :unprocessable_entity }
        format.json { render json: @list_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /list_items/1 or /list_items/1.json
  def destroy
    @list_item.destroy

    respond_to do |format|
      format.html { redirect_to list_items_url, notice: "List item was successfully destroyed." }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_list_item
      @list_item = ListItem.find(params[:id])
    end

    # Only allow a list of trusted parameters through.
    def list_item_params
      params.require(:list_item).permit(:first_name, :last_name, :email, :phone, :class_name)
    end

    def sort_column
      ListItem.column_names.include?(params[:sort]) ? params[:sort] : "id"
    end
  
    def sort_direction
      %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
    end
  
end

app/helpers/list_items_helper.rb
module ListItemsHelper
end

app/views/list_items/_form.html.erb
<%= form_with(model: list_item) do |form| %>
  <% if list_item.errors.any? %>
    <div style="color: red">
      <h2><%= pluralize(list_item.errors.count, "error") %> prohibited this list_item from being saved:</h2>

      <ul>
        <% list_item.errors.each do |error| %>
          <li><%= error.full_message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>
  <fieldset>
    <div class="form-group">
      <label for="exampleInputEmail1" class="form-label mt-4">First Name</label>
      <%= form.text_field :first_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1" class="form-label mt-4">Last Name</label>
      <%= form.text_field :last_name, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1" class="form-label mt-4">Email</label>
      <%= form.text_field :email, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1" class="form-label mt-4">Phone</label>
      <%= form.text_field :phone, class: "form-control" %>
    </div>
    <div class="form-group">
      <label for="exampleInputEmail1" class="form-label mt-4">Class Name</label>
      <%= form.text_field :class_name, class: "form-control" %>
    </div>
    <div class="mt-2 float-end">
      <%= form.submit :class => "btn btn-outline-success" %>
    </div>
  </fieldset>
<% end %>
</form>

app/views/list_items/_list_item.html.erb
<div id="<%= dom_id list_item %>">
  <p>
    <strong>First Name:</strong>
    <%= list_item.first_name %>
  </p>

  <p>
    <strong>Club:</strong>
    <%= list_item.last_name %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= list_item.email %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= list_item.phone %>
  </p>

  <p>
    <strong>Age:</strong>
    <%= list_item.class_name %>
  </p>

</div>

app/views/list_items/edit.html.erb
<h1>Editing list item</h1>

<%= render "form", list_item: @list_item %>

<br>

<div>
  <%= link_to "Show this list item", @list_item %> |
  <%= link_to "Back to list items", list_items_path %>
</div>

app/views/list_items/index.html.erb
<div id="list_items">
  <p class="h1 text-center">List items</p>
  <table class="table table-hover">
    <thead>
    <tr class="table bg-light">
      <th scope="col">#</th>
      <th scope="col"><%= sortable "first_name" %></th>
      <th scope="col">Las </th>
      <th scope="col">Item </th>
      <th scope="col">Item </th>
      <th scope="col">Item </th>
      <th scope="col" colspan="3" style="width: 15%">Action</th>
    </tr>
    </thead>
    <tbody>
    <% index = 1 %>
    <% @list_items.each do |list_item| %>
      <tr>
        <td><%= index %></td>
        <td><%= list_item.first_name %></td>
        <td><%= list_item.last_name %></td>
        <td><%= list_item.email %></td>
        <td><%= list_item.phone %></td>
        <td><%= list_item.class_name %></td>
        <td><%= link_to list_item do %>
            <i class="fa fa-eye"></i>
          <% end %>
        </td>
        <td><%= link_to edit_list_item_path(list_item.id) do %>
            <i class="fa fa-edit"></i>
          <% end %>
        </td>
        <td>
        <%= link_to list_item_path(list_item.id), data: {turbo_method: :delete, turbo_confirm: 'Are you sure?'} do %>
            <i class="fa fa-trash"></i>
          <% end %>
        </td>
      </tr>
      <% index += 1 %>
    <% end %>
    </tbody>
  </table>
  
</div>

<%= link_to new_list_item_path, class:"btn btn-outline-info" do%>
  <i class="fa fa-plus"></i> New item
<% end %>

app/views/list_items/new.html.erb
<h1>New list item</h1>

<%= render "form", list_item: @list_item %>

<br>

<div>
  <%= link_to "Back to list items", list_items_path %>
</div>

app/views/list_items/show.html.erb
<p style="color: green"><%= notice %></p>

<%= render @list_item %>